### ISSUE TITLE
Spacelift provider should be in the Terraform Registry

### ISSUE THREAD

**Issue by Gowiem** [spacelift-io/terraform-provider-spacelift#147]
## Info

I'm seeing the large majority of providers show up properly in the Terraform Registry nowadays since they've opened it up to everyone, but I don't see Spacelift show up there. The registry provides a great experience when viewing resource / data source documentation, so figured I'd suggest it here. 

Here are docs on making it happen: https://www.terraform.io/docs/registry/providers/docs.html

**Comment by Gowiem** [comment]
@marcinwyszynski for your consideration whenever ya'll get the chance 👍

**Comment by marcinwyszynski** [comment]
We're hesitant to have a dependency on a commercial entity that can view us as competitors. We'll be addressing the issue somewhat differently - please stay tuned for some other activity in this area.

**Comment by Gowiem** [comment]
@marcinwyszynski makes sense 👍
