### ISSUE TITLE
Plan time validation for resources

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#203]
## Plan time validation

It would be nice to have plan time validation. Here are some examples.

### Resource `spacelift_stack`

If the `repository`, `branch`, etc is misconfigured, it would throw an error on the plan instead of after the apply.

For example, if I put in the wrong `branch` or I forget the omit the owner from `repository`, I won't see it until after the apply.

Ways to validate

* Check if `repository` contains a forward slash meaning that an owner was accidentally provided
* Check if the repository exists
* Check if the branch exists
* It's possible that all of the above can be correct but spacelift github app may not have permissions. It would be good to suggest this in the error message thrown.

### Resource `spacelift_run`

Similar to `spacelift_stack`. 

* check if `commit_sha` exists

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/19078/files
* https://github.com/hashicorp/terraform-provider-aws/issues?page=2&q="validation"+is%3Amerged

**Comment by marcinwyszynski** [comment]
Unfortunately, this is only partially doable. Validation in Terraform is generally broken. Currently, it only has access to the value of a single field. So you can't use it to query an external source to see if the value is correct. Even worse, you can't validate multiple interdependent fields. For example, you can have scenarios if the validity of the value of field B may depend on the value of field A. Unfortunately, AFAIK there is no way you can validate it with Terraform.

So effectively, what we can validate here is:
- the format of the repository name (no forward slash present);
- the format of the branch (e.g., no whitespace);
- the commit SHA (length = 40, is hex);

These are trivial checks, though, and I'm not sure how useful they can be.

**Comment by marcinwyszynski** [comment]
Actually, I may be lying. Just had an AWS provider do something super cool for me (failure for a combination of parameters) and I can see that [they've used](https://github.com/hashicorp/terraform-provider-aws/blob/8c2e8ae9543ae5e84eabf6248982f79476355fd3/aws/resource_aws_sqs_queue.go#L395) [this trick](https://www.terraform.io/docs/extend/resources/customizing-differences.html) to get it to work.

**Comment by marcinwyszynski** [comment]
Unfortunately, it's not how that new API works. It's only useful in a handful of corner cases and we're unable to use it to perform plan-time validation against our endpoints.
