### ISSUE TITLE
Allow making the `branch` argument optional for `spacelift_stack`

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#204]
It would be nice if we could omit the `branch` argument for `spacelift_stack` and have it assume that we want to use the default branch of the given `repository`.

This would be helpful when org repos have different default branches (master, main, production, etc) so we don't end up making a mistake when creating new stacks for different repositories.

https://github.com/spacelift-io/terraform-provider-spacelift/blob/04983b9ff58237751a251cf4e6fe0ad5abe7b3d8/spacelift/resource_stack.go#L118-L122

**Comment by marcinwyszynski** [comment]
This is problematic in practice and potentially unnecessary.

What if the default branch changes? Do we point it to the new default branch? That would potentially change the infra definitions in a way that's not easily auditable. Or do we start failing until you manually point the stack to some other branch? Or do we keep using the same (though now non-default) branch?

It feels like a more straightforward solution would be to use GitHub's own Terraform provider and query their `github_repository ` data source for the [`default_branch`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository#default_branch) attribute. Then pass the value of the attribute to the Spacelift resource.

**Comment by nitrocode** [comment]
Oh ok I see what you mean. Thanks for acknowledging! I'll look into using a data source instead.
