### ISSUE TITLE
Error: Unexpected token issuer api-key, is this a Spacelift run?

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#283]
I tried running a spacelift terraform module locally.

I have this in my hcl which works in spacelift

```hcl
provider "spacelift" {}
```

Locally, I set the following inputs

```console
export SPACELIFT_API_KEY_ENDPOINT=https://snip.app.spacelift.io
export SPACELIFT_API_KEY_ID=snip
export SPACELIFT_API_KEY_SECRET=snip
```

I get the following error when I do a `terraform init && terraform plan`

```hcl
 Error: unexpected token issuer api-key, is this a Spacelift run?
│
│   with module.spacelift.data.spacelift_current_stack.administrative[0],
│   on .terraform/modules/spacelift/main.tf line 167, in data "spacelift_current_stack" "administrative":
│  167: data "spacelift_current_stack" "administrative" {
```

Followed this guide https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs#running-outside-of-spacelift

**Comment by michieldewilde** [comment]
Hi.

You are using the [spacelift_current_stack](https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/data-sources/current_stack) resource which requires that the run is executed within Spacelift by a stack or a module.

**Comment by nitrocode** [comment]
Oh I see, thank you!
