### ISSUE TITLE
Request: `spacelift_stacks` (plural) data source

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#288]
The current `spacelift_stack` data source is nice but it will fail if the stack cannot be found.

If there is a `spacelift_stacks` data source, much like [`aws_iam_roles`](https://registry.terraform.io/providers/hashicorp/aws/3.75.1/docs/data-sources/iam_roles) data source, then we can try to find a stack and if it fails, it can quietly return zero results.

Use case, see differences between what our current label is with what the new label is.

If the current label is a shasum of a non-committed mounted file and the new label is a new shasum of the changed non-committed mounted file, then we can use `spacelift_run` to trigger it.

**Comment by wojciech12** [comment]
@nitrocode  That is a great suggestion. We will add the support for `spacelift_stacks` (plural) data source to our backlog, but I cannot tell at this moment when we will implement it.

**Comment by peterdeme** [comment]
Implemented in https://github.com/spacelift-io/terraform-provider-spacelift/pull/382

**Comment by nitrocode** [comment]
Thank you!
