### ISSUE TITLE
[bug] spacelift_module name destroy cycle

### ISSUE THREAD

**Issue by SizZiKe** [spacelift-io/terraform-provider-spacelift#290]
if you specify `name = "test module"` (or any other name with spaces) for the `spacelift_module` resource you will end up in a constant cycle of replacement. The name ends up being a calculated value matching the ID for the module, which causes a permanent difference if the name does not end up matching the module ID exactly.

E.g.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/6923208/168384893-eb75cb65-5598-4948-89fc-2f3062b5704c.png">

**Comment by cube2222** [comment]
Hey @SizZiKe! This should now be properly handled.
