### ISSUE TITLE
Policy labels cannot be removed via terraform

### ISSUE THREAD

**Issue by lexton** [spacelift-io/terraform-provider-spacelift#297]
## Scope

I think the same may apply to stacks & modules as well - but I didn't test this out.

## Description 

* I previously had labels applied via terraform
* I removed said labels from source code
* It generates a diff like so:
``` text
  # module.global_policy.spacelift_policy.policy["plan.no_iam_users.rego"] will be updated in-place
  ~ resource "spacelift_policy" "policy" {
        id     = "global-no_iam_users"
      ~ labels = [
          - "autoattach:meta:all",
        ]
        name   = "name"
        # (2 unchanged attributes hidden)
    }
```
The label changes are not actually applied.

## Relevant Code:

https://github.com/spacelift-io/terraform-provider-spacelift/blob/main/spacelift/resource_policy.go#L164

I believe what is happening is:

* Existing labels are fetched
* New labels are picked up from the config and appended
* There is no true up of labels that exist that aren't in terraform code

## What should have happened

* Labels that were removed should have been removed

**Comment by adamconnelly** [comment]
@lexton you're correct - this is an edge-case that happens when *all* labels are removed from a policy. In that case we end up sending through `null` to the API, which ignores the change.

Thanks for reporting this :bow:

**Comment by adamconnelly** [comment]
Just a quick update on this, I've confirmed that Policies, Contexts and Worker Pools are affected by this. Stacks and Modules are not.

The fix actually needs to be made in the GraphQL API rather than the Terraform provider, but I'm going to add test cases to reproduce the issue.

**Comment by adamconnelly** [comment]
@lexton just to let you know that the problem should be fixed now. The fix was made to our GraphQL API rather than the Terraform provider, so you don't need to do anything to get the fix - it should just automatically start working.

I'm closing this issue now, but feel free to reopen if the issue hasn't been resolved for you.
