### ISSUE TITLE
Support `API keys` management

### ISSUE THREAD

**Issue by tiwood** [spacelift-io/terraform-provider-spacelift#312]
Please consider support for API key operations.

* Create new API keys
* Delete/Revoke API keys

**Comment by jmfontaine** [comment]
Hi @tiwood !

That is a great suggestion. Let me talk to the engineering team.

**Comment by wojciech12** [comment]
Hi @tiwood, thank you for your suggestion. We do not plan to support API keys operations through the provider because of security reasons. Users should go through the authentication process to generate the keys.
