### ISSUE TITLE
Request: `spacelift_policy_attachment` verifies `policy_id` exists during plan time

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#399]
It would be nice if `spacelift_policy_attachment` verifies that the `policy_id` exists during plan time so we do not have to verify its existence with a data source.

This would allow us to see errors during the plan time if someone made a `policy_id` typo.

**Comment by marcinwyszynski** [comment]
I'm afraid that there is no way to tell the Terraform provider to talk to the external API during the planning phase for a resource that does not yet exist (has no ID set).
