### ISSUE TITLE
Add the ignore state bool to spacelift_drift_detection resource 

### ISSUE THREAD

**Issue by duganth** [spacelift-io/terraform-provider-spacelift#414]
Recently there was a boolean added to the drift detection settings to ignore state. We would like to use that feature in terraform. This issue is to track when that is added to the terraform provider so we can update our stack configuration. Thank you!

**Comment by peterdeme** [comment]
@duganth here it is https://github.com/spacelift-io/terraform-provider-spacelift/pull/415

**Comment by tomasmik** [comment]
Included in v1.0.1
