### ISSUE TITLE
Error "could not update space: unauthorized - is it an administrative stack in the root space?"

### ISSUE THREAD

**Issue by nitrocode** [spacelift-io/terraform-provider-spacelift#424]
From this terraform plan change within an admin stack run

```hcl
  # module.spacelift.module.stacks["gbl-corp-infrastructure-snip"].spacelift_space.default[0] will be updated in-place
  ~ resource "spacelift_space" "default" {
        id               = "infrastructure-snip"
      ~ labels           = [
          - "deps:stacks/orgs/snip/mgmt/_defaults.yaml",
            # (8 unchanged elements hidden)
        ]
        name             = "infrastructure-snip"
        # (2 unchanged attributes hidden)
    }
```

We receive this error when trying to update a `spacelift_space` in terraform.

```hcl
╷
│ Error: could not update space: unauthorized - is it an administrative stack in the root space?
│ 
│   with module.spacelift.module.stacks["gbl-corp-infrastructure-snip"].spacelift_space.default[0],
│   on .terraform/modules/spacelift/modules/stack/main.tf line 221, in resource "spacelift_space" "default":
│  221: resource "spacelift_space" "default" {
│ 
```

The spacelift space was created by terraform but it cannot be modified with terraform. I'm unsure if this is a spacelift terraform issue or a spacelift API issue, or maybe even a permissions issue.

The spacelift space is called `flex` and it's part of the `infrastructure` space which inherits from the `root` space.

The workaround was to no-op the terraform by clickops'ing the change within Spacelift.

## references

- https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/space

**Comment by AtzeDeVries** [comment]
Also got into this issue, but according to docs to manage spaces the stack needs to be in the root space https://docs.spacelift.io/concepts/spaces/access-control#roles

**Comment by Yantrio** [comment]
closing as this was answered by @AtzeDeVries , please feel free to re-open if you are still hitting issues.

**Comment by borisceranic** [comment]
I have encountered this same issue while instructing a Stack in a root space to move Stack from the root space to another sub-space.

Turns out I also referred to the sub-space by its name, instead of by its id.

I believe that an error message could greatly reduce friction here, by telling users that `the space_id "such-and-such" does not exist, and maybe you forgot are referring to the space by its name instead of by its id?`

**Comment by AkselAllas** [comment]
If you are trying to create a space inside a non-root space using a non-root API key, then this setting might need to be enabled inside organization settings.

<img width="727" height="348" alt="Image" src="https://github.com/user-attachments/assets/6e821289-ff8e-47bb-a43b-d286b3692981" />
