### ISSUE TITLE
Add tail option to spacelift_run resource

### ISSUE THREAD

**Issue by jwenz723** [spacelift-io/terraform-provider-spacelift#427]
I have a terraform module which creates stacks in spacelift using the `spacelift_stack` terraform resource. I am trying to create an automated test for my module using the spacelift module registry. The test runs my module, which causes the child stacks to be created, but it does not automatically run the child stacks. In my test I would like to run the child stacks so that I can validate they are configured properly.

I am able to use the `spacelift_run` resource to trigger the child stacks to run, but there is not a way for me to know when the run has completed. I need to know when the run has completed so that my automated test can destroy the child stacks.

**Comment by Yantrio** [comment]
This was added in #535 and released in v1.11.0 https://github.com/spacelift-io/terraform-provider-spacelift/releases/tag/v1.11.0
