### ISSUE TITLE
How to run tests locally?

### ISSUE THREAD

**Issue by leetrout** [spacelift-io/terraform-provider-spacelift#468]
Can y'all add a note to the README about how someone outside of spacelift can run the tests?

Looks like it expects repos named `demo` and `terraform-bacon-tasty` to exist?

I see similar references from @marcinwyszynski in https://github.com/hashicorp/terraform-provider-random/issues/125 so perhaps this a personal repo?

Maybe share the repo? Or a small blurb about what should be in it? Or make the repo names configurable in the tests?

**Comment by Yantrio** [comment]
Hi! this needs some work on our side to be a bit easier for people to use as some of the tests currently make assumptions about the spacelift account as you mentioned. We will be attempting to improve this over time as we add tests however its difficult to decouple a large amount of existing code right now.

I recommend in the meantime to run only individual tests for areas that you are contributing to and if you hit any snags please feel free to reach out! Sorry for the inconvenience.
