### ISSUE TITLE
Creation of `spacelift_user` resource results in "get login from session: incompatible issuer" error

### ISSUE THREAD

**Issue by mgajewskik** [spacelift-io/terraform-provider-spacelift#486]
I have tried to use the [spacelift_user](https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/user) resource on my account created from GitHub organization in 2 different ways: 
- adding a completely new user (which exists in my GitHub org)
- passing in user that already exists in the Spacelift account as a way to change the manually assigned policy

Both cases fail with this error:
```
[01HH1TMVXW5QDAEZTNQWKV9A2E] Applying changes...
spacelift_user.mgajewskik: Creating...
╷
│ Error: could not create user mapping mgajewskik: get login from session: incompatible issuer
│ 
│   with spacelift_user.mgajewskik,
│   on users.tf line 2, in resource "spacelift_user" "mgajewskik":
│    2: resource "spacelift_user" "mgajewskik" {
│ 
╵
[01HH1TMVXW5QDAEZTNQWKV9A2E] Unexpected exit code when applying changes: 1
```
Resource definition I'm using:
```
resource "spacelift_user" "test" {
  username         = "mgajewskik"
  invitation_email = "<email>"

  policy {
    role     = "ADMIN"
    space_id = "root"
  }
}
```
I'm not sure at this point if there is something wrong with the provider itself or if I'm using it incorrectly. Any guidance on that? Thanks!

**Comment by marcinwyszynski** [comment]
I was able to reproduce it, assigning to our dev teams for a fix.

**Comment by marcinwyszynski** [comment]
This has just been fixed.
