### ISSUE TITLE
AWS Integration: "could not attach the aws integration" -- back off issue?

### ISSUE THREAD

**Issue by mheffner** [spacelift-io/terraform-provider-spacelift#493]
When I'm attempting to attach an AWS integration (`spacelift_aws_integration_attachment`) to a stack, it is failing with:

```
 Error: could not attach the aws integration: you need to configure trust relationship section in your AWS account
```

It appears to fail immediately. If I look at the code, it looks like it should enter a back-off loop, but I'm not seeing it hit the sleep wait here. My guess is it is hitting that error code string check and bailing early.
https://github.com/spacelift-io/terraform-provider-spacelift/blob/4d3a0727330fbfc84c3e1a3aaf02dc820b8c23ae/spacelift/resource_aws_integration_attachment.go#L80-L88

I was able to get it to work by immediately re-running the `apply`. This seems to imply the failure was timing based and not a configuration error.

**Comment by FidelusAleksander** [comment]
We are having the same issue. It occurs always on the initial stack creation. Re-running always helps, but this is still annoying

**Comment by alexjurkiewicz** [comment]
You can add an explicit wait in your local Terraform code:

```terraform
resource "aws_iam_role" "this" {
  # ...
}
resource "time_sleep" "wait_for_iam_eventual_consistency" {
  depends_on      = [aws_iam_role.this]
  create_duration = "15s"
}
resource "spacelift_aws_integration" "this" {
  # ...
  depends_on = [time_sleep.wait_for_iam_eventual_consistency]
}
```
I've found 15 secs is typically enough in our environment.
