### ISSUE TITLE
Refresh fails when a manually space is removed from the Terraform configuration

### ISSUE THREAD

**Issue by HighwayofLife** [spacelift-io/terraform-provider-spacelift#550]
### Description:
When a Spacelift resource (e.g., a space) is manually deleted outside of Terraform (such as through the Spacelift UI) and the corresponding resource block is removed from the Terraform configuration, the `terraform plan` stage fails during the refresh stage. This prevents the execution from proceeding to the apply stage, even though the state should ideally match the updated configuration.

### Steps to Reproduce:

1. Create a Spacelift resource (e.g., a space) using Terraform.
2. Manually delete the resource from the Spacelift UI or API.
3. Remove the corresponding resource block from the Terraform configuration.
4. Run spacelift on the stack, which will run`terraform plan` to refresh the state and plan the changes.

### Expected Behavior:

When a resource is manually deleted and the corresponding resource block is removed from the Terraform configuration, the refresh stage should update the state to match the configuration. The `terraform plan` stage should succeed, allowing the execution to proceed to the apply stage, as the state and configuration are now in sync.

### Actual Behavior:
The `terraform plan` stage fails during the refresh stage with an error indicating that the resource cannot be found. This prevents the execution from proceeding to the apply stage, even though the state should be updated to match the modified configuration.

### Error Message:
```
Error: Error acquiring the state lock

Error message: resource not found
```

### Additional Context:
Even when attempting to remove the resource from the state using `terraform state rm`, the command fails with an error:

```
$ terraform state rm spacelift_space.account-space
╷
│ Error: Error acquiring the state lock
│
│ Error message: resource not found
```

Using the `-lock=false` option with `terraform state rm` removes the resource from the state, but the state cannot be saved, and no backup is created:

```
$ terraform state rm -lock=false spacelift_space.account-space
Removed spacelift_space.account-space
Error saving the state: Error uploading state: cannot create state version

The state was not saved. No items were removed from the persisted
state. No backup was created since no modification occurred. Please
resolve the issue above and try again.
```

This issue prevents users from properly managing their Spacelift resources when manual deletions occur, as they cannot update the state to match the modified configuration.
Please investigate this issue and provide a resolution to allow the refresh stage to handle manually deleted resources gracefully when the corresponding resource blocks are removed from the Terraform configuration.

### Possible Solution:
The Spacelift provider should implement robust error handling and state management mechanisms to address scenarios where managed resources are externally deleted. This could involve:
- Improved Refresh Logic: Enhance the refresh logic to detect and handle deleted resources gracefully, updating the state accordingly without causing errors.
- State Removal Fixes: Address the issues preventing successful removal of deleted resources from the state using terraform state rm.

### Workaround:
As a temporary workaround, users can manually edit the Terraform state file to remove the entry corresponding to the deleted space. However, this approach is not recommended as it can lead to inconsistencies and should be used with caution, and uploading the state is a cumbersome and error-prone task.

**Comment by marcinwyszynski** [comment]
Looking at the error message, my feeling is that you have Spacelift "remote" state backend configuration explicitly declared in your code?

**Comment by HighwayofLife** [comment]
> Looking at the error message, my gut feeling is that you have Spacelift "remote" state backend configuration explicitly declared in your code?

Since it was failing, I added a backend code to attempt to remove the item from state using `terraform rm` command locally. But it failed in both situations.

**Comment by marcinwyszynski** [comment]
Spacelift's built-in state backend does not perform locking because that's already handled by Spacelift's state machine. The failure mode that you're seeing is unlikely to be caused directly by the provider, it's more likely a backend misconfiguration. I would suggest discussing that explicitly on Slack or even getting on a quick call with one of our Solutions or Support people.

**Comment by marcinwyszynski** [comment]
To clarify, by closing this as "working as intended" I only mean to say that the failure mode is unrelated to the provider.
