### ISSUE TITLE
enable_well_known_secret_masking  Has no default and breaks existing stacks with no warning of this change in the release notes

### ISSUE THREAD

**Issue by crouth-redge** [spacelift-io/terraform-provider-spacelift#558]
The new [enable_well_known_secret_masking](https://registry.terraform.io/providers/spacelift-io/spacelift/1.13.1/docs/resources/stack#enable_well_known_secret_masking) option merged in #553 was not given a default value for the bool, breaking all existing stack pipelines without warning when updating to the latest release.

This should have a default to ensure backwards compatibility, or be explicitly declared as a breaking change.

```
 Error: could not query for stack: Cannot query field "enableWellKnownSecretMasking" on type "Stack".
 
   with spacelift_stack.rcon_i1_ecs,
   on env_i1_aws_stacks.tf line 265, in resource "spacelift_stack" "rcon_i1_ecs":
  265: resource "spacelift_stack" "rcon_i1_ecs" {
 
```

**Comment by crouth-redge** [comment]
Actually this is something else - setting the bool does not work around it, and dropping down to `1.13.0` from `1.13.1` resulted in:

```
╷
│ Error: could not query for stack dependency reference: Cannot query field "triggerAlways" on type "StackDependencyReference".
│ 
│   with spacelift_stack_dependency_reference.rcon_i1_dns_d1_dns,
│   on env_i1_aws_stacks.tf line 165, in resource "spacelift_stack_dependency_reference" "rcon_i1_dns_d1_dns":
│  165: resource "spacelift_stack_dependency_reference" "rcon_i1_dns_d1_dns" {
│ 
╵
```

I had to drop back to 1.12.0 to get anything working in our on prem instance.

**Comment by ilya-hontarau** [comment]
@crouth-redge Thank you for reporting this issue.

If you're using a self-hosted version, there might be a situation where the Terraform client is ahead of the self-hosted version. Please refer to this compatibility [matrix](https://docs.spacelift.io/self-hosted/latest/vendors/terraform/terraform-provider.html#self-hosted-version-compatibility) to ensure you use the supported version.
