### ISSUE TITLE
Change spacelift_environment_variable value to choose between secret or plaintext

### ISSUE THREAD

**Issue by victor-efedi-sympower** [spacelift-io/terraform-provider-spacelift#562]
It will be cool to be able to choose if a `TF_VAR` from `spacelift_environment_variable` can be a secret or plaintext since this is available on the UI. 

Passing a file path using `spacelift_environment_variable` and it is masked with "*" and we now have to go to the UI to change this. 

So something like below 
```hcl

variable "relative_path" {
  description = "Relative path to file"
  type        = string
  default     = "../dir"
}

resource "spacelift_environment_variable" "relative_path" {
  stack_id = spacelift_stack.test.id
  name     = "TF_VAR_relative_path"
  value    = "../../dir"
  sensitive = false
}
```

**Comment by Yantrio** [comment]
The field you are looking for here is [write_only](https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/environment_variable#write_only)
